(function(){var f=true,g=null,h=false,aa=encodeURIComponent,i=window,ba=Object,k=navigator,ca=undefined,l=parseInt,da=String,n=document,ea=decodeURIComponent,o=Math;function fa(a,b){return a.width=b}function ga(a,b){return a.toString=b}function ha(a,b){return a.height=b}
var ia="appendChild",p="push",ja="valueOf",ka="width",la="round",ma="slice",r="replace",na="floor",oa="cookie",pa="charAt",qa="_height_",s="indexOf",u="write",ra="domain",sa="match",ua="opera",v="_html_",va="createElement",w="getParameter",wa="addEventListener",xa="referrer",ya="attachEvent",za="name",Aa="contentWindow",Ba="getTime",Ca="getElementsByTagName",x="toString",y="length",Da="propertyIsEnumerable",Ea="plugins",z="prototype",Fa="setTimeout",A="document",B="split",C="userAgent",D="screen",
E="style",Ga="body",Ha="_width_",F="call",G="random",Ia="_is_afc_",H="substring",Ja="navigator",Ka="parentNode",La="height",I="join",Ma="toLowerCase",J=this,Na=function(a,b,c){a=a[B](".");c=c||J;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[y]&&(d=a.shift());)if(!a[y]&&b!==ca)c[d]=b;else c=c[d]?c[d]:(c[d]={})},Oa=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof ba)&&ba[z][x][F](a)=="[object Array]"||typeof a[y]=="number"&&typeof a.splice!="undefined"&&
typeof a[Da]!="undefined"&&!a[Da]("splice"))return"array";if(!(a instanceof ba)&&(ba[z][x][F](a)=="[object Function]"||typeof a[F]!="undefined"&&typeof a[Da]!="undefined"&&!a[Da]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[F]=="undefined")return"object";return b};o[na](o[G]()*2147483648)[x](36);
var Pa=function(a,b){var c=b||J;if(arguments[y]>2){var d=Array[z][ma][F](arguments,2);return function(){var e=Array[z][ma][F](arguments);Array[z].unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},K=function(a,b,c){Na(a,b,c)},Qa=function(a,b,c){a[b]=c},Ra=function(a,b){function c(){}c.prototype=b[z];a.Ca=b[z];a.prototype=new c};var Sa=function(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c},Ta=function(a,b){if(a=="true")return f;if(a=="false")return h;return b},Ua=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,Va=function(a,b){if(!a)return b;var c=a[sa](Ua);return c?c[0]:b};var Wa=function(){return Va("","pagead2.googlesyndication.com")};var Za=function(a){if(a[s]("&")!=-1)return"document"in J&&a[s]("<")==-1?Xa(a):Ya(a);return a},Xa=function(a){var b=J[A][va]("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},Ya=function(a){return a[r](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c[pa](0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return da.fromCharCode(d)}return b}})},ab=function(a,b){for(var c=
0,d=da(a)[r](/^[\s\xa0]+|[\s\xa0]+$/g,"")[B]("."),e=da(b)[r](/^[\s\xa0]+|[\s\xa0]+$/g,"")[B]("."),m=o.max(d[y],e[y]),j=0;c==0&&j<m;j++){var q=d[j]||"",t=e[j]||"",ta=new RegExp("(\\d*)(\\D*)","g"),T=new RegExp("(\\d*)(\\D*)","g");do{var U=ta.exec(q)||["","",""],V=T.exec(t)||["","",""];if(U[0][y]==0&&V[0][y]==0)break;c=U[1][y]==0?0:l(U[1],10);var hb=V[1][y]==0?0:l(V[1],10);c=$a(c,hb)||$a(U[2][y]==0,V[2][y]==0)||$a(U[2],V[2])}while(c==0)}return c},$a=function(a,b){if(a<b)return-1;else if(a>b)return 1;
return 0};var bb=function(a,b){fa(this,a);ha(this,b)};bb[z].floor=function(){fa(this,o[na](this[ka]));ha(this,o[na](this[La]));return this};bb[z].round=function(){fa(this,o[la](this[ka]));ha(this,o[la](this[La]));return this};var cb,db,eb,fb,gb,ib,jb,kb,lb,mb=function(){return J[Ja]?J[Ja][C]:g},nb=function(){return J[Ja]},ob=function(){gb=fb=eb=db=cb=h;var a;if(a=mb()){var b=nb();cb=a[s]("Opera")==0;db=!cb&&a[s]("MSIE")!=-1;fb=(eb=!cb&&a[s]("WebKit")!=-1)&&a[s]("Mobile")!=-1;gb=!cb&&!eb&&b.product=="Gecko"}};ob();
var pb=cb,qb=db,rb=gb,sb=eb,tb=fb,ub=function(){var a=nb();return a&&a.platform||""},vb=ub(),wb=function(){ib=vb[s]("Mac")!=-1;jb=vb[s]("Win")!=-1;kb=vb[s]("Linux")!=-1;lb=!!nb()&&(nb().appVersion||"")[s]("X11")!=-1};wb();var xb=function(){var a="",b;if(pb&&J[ua]){a=J[ua].version;a=typeof a=="function"?a():a}else{if(rb)b=/rv\:([^\);]+)(\)|;)/;else if(qb)b=/MSIE\s+([^\);]+)(\)|;)/;else if(sb)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(mb()))?a[1]:""}return a},yb=xb(),zb={};var Ab=function(a){var b=a[A];if(sb&&!(zb["500"]||(zb["500"]=ab(yb,"500")>=0))&&!tb){if(typeof a.innerHeight=="undefined")a=i;b=a.innerHeight;var c=a[A].documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new bb(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"&&(!pb||pb&&(zb["9.50"]||(zb["9.50"]=ab(yb,"9.50")>=0)))?b.documentElement:b[Ga];return new bb(a.clientWidth,a.clientHeight)};var Bb=n,L=i,Cb=function(a){var b=g;if((a=a[Ca]("script"))&&a[y]){b=a[a[y]-1];b=b[Ka]}return b};Cb(Bb);var Db="http://"+Wa()+"/pagead/show_ads.js";function M(a){return typeof aa=="function"?aa(a):escape(a)}function Eb(a,b,c){var d=n[va]("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=n[Ca]("head")[0];if(!e)return h;i[Fa](function(){e[ia](d)},0);return f}function Fb(a,b){if(a[ya]){a[ya]("onload",b);return f}if(a[wa]){a[wa]("load",b,h);return f}return h}var Gb=function(a){if(!("google_onload_fired"in a)){a.google_onload_fired=h;Fb(a,function(){a.google_onload_fired=f})}};
function Hb(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests[p](c)}function Ib(a){if(a in Jb)return Jb[a];return Jb[a]=k[C][Ma]()[s](a)!=-1}var Jb={};function Kb(){return Ib("msie")&&!i[ua]}
function Lb(){if(k[Ea]&&k.mimeTypes[y]){var a=k[Ea]["Shockwave Flash"];if(a&&a.description)return a.description[r](/([a-zA-Z]|\s)+/,"")[r](/(\s)+r/,".")}else if(k[C]&&k[C][s]("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a[x]()}else if(Kb()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==
6)return a[x]()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(m){}}if(b){a=b.GetVariable("$version")[B](" ")[1];return a[r](/,/g,".")}}return"0"}function Mb(a,b){if(!(o[G]()<1.0E-4)){var c=o[G]();if(c<b){c=o[na](c/b*a[y]);return a[c]}}return""}
var Nb=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=i.history[y];a.u_java=k.javaEnabled();if(i[D]){a.u_h=i[D][La];a.u_w=i[D][ka];a.u_ah=i[D].availHeight;a.u_aw=i[D].availWidth;a.u_cd=i[D].colorDepth}if(k[Ea])a.u_nplug=k[Ea][y];if(k.mimeTypes)a.u_nmime=k.mimeTypes[y]},Ob=function(a,b){var c=b||L;if(a&&c.top!=c)c=c.top;try{return c[A]&&!c[A][Ga]?new bb(-1,-1):Ab(c||i)}catch(d){return new bb(-12245933,-12245933)}},Pb=function(a,b){var c=a[y];if(c==0)return 0;for(var d=b||305419896,e=0;e<
c;e++){var m=a.charCodeAt(e);d^=(d<<5)+(d>>2)+m&4294967295}return d>0?d:4294967296+d},Qb=function(a){if(a==a.top)return 0;var b=[];b[p](a[A].URL);a[za]&&b[p](a[za]);var c=f;a=Ob(!c,a);b[p](a[ka][x]());b[p](a[La][x]());return Pb(b[I](""))},Rb=function(a){if(!a)return"";var b=[],c=0;for(a=a;a&&c<25;a=a[Ka],++c)b[p](a.id||"");return b[I]()};var Sb=Sa("0.1",0);var Tb=Sa("0.005",0),Ub=Sa("0.01",0),Vb=Sa("0.01",0),Wb=Sa("0.001",0),Xb=Sa("0.006",0),Yb=Sa("0.008",0);var Zb=Ta("false",h),$b=Ta("false",h),ac=Ta("false",h),bc=Ta("false",h);var cc=function(a,b,c){b=Pa(b,J,a);a=i.onerror;i.onerror=b;try{c()}catch(d){c=d[x]();var e="";if(d.fileName)e=d.fileName;var m=-1;if(d.lineNumber)m=d.lineNumber;b=b(c,e,m);if(!b)throw d;}i.onerror=a};K("google_protectAndRun",cc);
var ec=function(a,b,c,d){if(o[G]()<0.01){var e=Bb;a=["http://",Va("","pagead2.googlesyndication.com"),"/pagead/gen_204","?id=jserror","&jscb=",Zb?1:0,"&jscd=",$b?1:0,"&context=",M(a),"&msg=",M(b),"&file=",M(c),"&line=",M(d[x]()),"&url=",M(e.URL[H](0,512)),"&ref=",M(e[xa][H](0,512))];a[p](dc());Hb(L,a[I](""))}return!ac};K("google_handleError",ec);
var dc=function(){var a=["&client=",M(L.google_ad_client),"&format=",M(L.google_ad_format),"&slotname=",M(L.google_ad_slot),"&output=",M(L.google_ad_output),"&ad_type=",M(L.google_ad_type)];return a[I]("")};var N=function(){this.Z=[];this.ra=i;this.v=0},fc=function(a,b){this.fn=a;this.win=b};N[z].enqueue=function(a,b){this.Z[p](new fc(a,b||this.ra));gc(this)};N[z].Y=function(){this.v=1};N[z].$=function(){if(this.v==1)this.v=0;gc(this)};Qa(N[z],"nq",N[z].enqueue);Qa(N[z],"al",N[z].Y);Qa(N[z],"rl",N[z].$);var gc=function(a){a.ra[Fa](Pa(a.qa,a),0)};N[z].qa=function(){if(this.v==0&&this.Z[y]){var a=this.Z.shift();this.v=2;a.win[Fa](Pa(this.oa,this,a),0);gc(this)}};N[z].oa=function(a){this.v=0;a.fn()};var hc,ic,jc,kc,lc,mc,nc,oc=function(){nc=mc=lc=kc=jc=ic=hc=h;var a=mb();if(a)if(a[s]("Firefox")!=-1)hc=f;else if(a[s]("Camino")!=-1)ic=f;else if(a[s]("iPhone")!=-1||a[s]("iPod")!=-1)jc=f;else if(a[s]("iPad")!=-1)kc=f;else if(a[s]("Android")!=-1)lc=f;else if(a[s]("Chrome")!=-1)mc=f;else if(a[s]("Safari")!=-1)nc=f};oc();var pc=!!i.google_async_iframe_id,qc=pc&&i.parent||i;var O=function(a){this.C=a;this.W=[];this.V=0;this.I=[];this.ja=0;this.O=[];this.ia=h;this.f=this.fa="";this.ha=h},rc=function(a,b,c){var d=a.C[c],e=a.W;a.C[c]=function(m){if(m&&m[y]>0){var j=m[y]>1?m[1].url:g;e[p]([b,Za(m[0].url),j])}d(m)}},sc=function(a){a.V++},tc=function(a,b){a.I[p](b)},uc="http://"+Wa()+"/pagead/osd.js",vc=function(a){if(!a.ia){Gb(qc);Eb(uc);a.ia=f}},wc=function(a,b){if(a.V>0)for(var c=a.C[A][Ca]("iframe"),d=a.ha?"google_ads_iframe_":"google_ads_frame",e=0;e<c[y];e++){var m=
c.item(e);m.src&&m[za]&&m[za][s](d)==0&&b(m,m.src)}},xc=function(a,b){var c=a.W;if(c[y]>0)for(var d=a.C[A][Ca]("a"),e=0;e<d[y];e++)for(var m=0;m<c[y];m++)if(d.item(e).href==c[m][1]){var j=d.item(e)[Ka];if(c[m][2])for(var q=j,t=0;t<4;t++){if(q.innerHTML[s](c[m][2])>0){j=q;break}q=q[Ka]}b(j,c[m][0]);c.splice(m,1);break}},zc=function(a,b){for(var c=0;c<a.I[y];c++){var d=a.I[c],e=yc(d);if(e)(e=a.C[A].getElementById("google_ads_div_"+e))&&b(e,d)}};O[z].T=function(a){xc(this,a);zc(this,a);wc(this,a)};
O[z].setupOsd=function(a,b,c){this.ja=a;this.fa=b;this.f=c};O[z].getOsdMode=function(){return this.ja};O[z].getEid=function(){return this.fa};O[z].getCorrelator=function(){return this.f};O[z].U=function(){return this.W[y]+this.V+this.I[y]};O[z].setValidOutputTypes=function(a){this.O=a};
O[z].registerAdBlockByType=function(a,b,c){if(this.O[y]>0){for(var d=0;d<this.O[y];d++)if(this.O[d]==a){this.ha=c;if(a=="js")rc(this,b,"google_ad_request_done");else if(a=="html")sc(this);else a=="json_html"&&tc(this,b)}vc(this)}};var yc=function(a){if((a=a[sa](/[&\?](?:slotname)=([^&]+)/))&&a[y]==2)return a[1];return""},Ac=function(){var a=qc;a.__google_ad_urls||(a.__google_ad_urls=new O(a));return a.__google_ad_urls};K("Goog_AdSense_getAdAdapterInstance",Ac);K("Goog_AdSense_OsdAdapter",O);
K("Goog_AdSense_OsdAdapter.prototype.numBlocks",O[z].U);K("Goog_AdSense_OsdAdapter.prototype.findBlocks",O[z].T);K("Goog_AdSense_OsdAdapter.prototype.getOsdMode",O[z].getOsdMode);K("Goog_AdSense_OsdAdapter.prototype.getEid",O[z].getEid);K("Goog_AdSense_OsdAdapter.prototype.getCorrelator",O[z].getCorrelator);K("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",O[z].setValidOutputTypes);K("Goog_AdSense_OsdAdapter.prototype.setupOsd",O[z].setupOsd);
K("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",O[z].registerAdBlockByType);var Bc={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Cc={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",
google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",
google_skip:"skip"},Dc={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var Ec=n,P=k,Q=i;
function Fc(){var a=Ec[oa],b=o[la]((new Date)[Ba]()/1E3),c=Q.google_analytics_domain_name;c=typeof c=="undefined"?Gc("auto"):Gc(c);var d=a[s]("__utma="+c+".")>-1,e=a[s]("__utmb="+c)>-1,m=a[s]("__utmc="+c)>-1,j={},q=!!Q&&!!Q.gaGlobal;if(d){a=a[B]("__utma="+c+".")[1][B](";")[0][B](".");j.sid=e&&m?a[3]+"":q&&Q.gaGlobal.sid?Q.gaGlobal.sid:b+"";j.vid=a[0]+"."+a[1];j.from_cookie=f}else{j.sid=q&&Q.gaGlobal.sid?Q.gaGlobal.sid:b+"";j.vid=q&&Q.gaGlobal.vid?Q.gaGlobal.vid:(o[la](o[G]()*2147483647)^Hc()&2147483647)+
"."+b;j.from_cookie=h}j.dh=c;j.hid=q&&Q.gaGlobal.hid?Q.gaGlobal.hid:o[la](o[G]()*2147483647);return Q.gaGlobal=j}function Hc(){var a=Ec[oa]?Ec[oa]:"",b=Q.history[y],c,d=[P.appName,P.version,P.language?P.language:P.browserLanguage,P.platform,P[C],P.javaEnabled()?1:0][I]("");if(Q[D])d+=Q[D][ka]+"x"+Q[D][La]+Q[D].colorDepth;else if(Q.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c[D][ka]+"x"+c[D][La]}d+=a;d+=Ec[xa]?Ec[xa]:"";for(a=d[y];b>0;)d+=b--^a++;return Ic(d)}
function Ic(a){var b=1,c=0,d;if(!(a==ca||a=="")){b=0;for(d=a[y]-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Gc(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Ec[ra];if("www."==a[H](0,4))a=a[H](4,a[y])}return Ic(a[Ma]())};function Jc(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=n[ra]}ga(Jc[z],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function Kc(){this.w=Lc(this);this.Q=h;if(!this.w)this.Q=Mc(this)}Kc[z].P="__gads=";Kc[z].D="GoogleAdServingTest=";Kc[z].M=function(a){this.q=a._cookies_[0];if(this.q!=g){this.w=this.q._value_;Nc(this)}};Qa(Kc[z],"setCookieInfo",Kc[z].M);
var Oc=function(a,b){var c=(new Date)[ja](),d=new Date;d.setTime(c+b);return d},Pc=function(a){var b=15552E6;a=Oc(a,b);b="ID=12345:T="+b;var c="/",d=n[ra];return new Jc(b,a[ja](),c,d)},Qc="http://"+Va("","partner.googleadservices.com")+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",Rc=function(a,b){if(!(a.w||!a.Q)){var c="script",d=n[ra];d=Qc+"&client="+M(b)+"&domain="+M(d);n[u]("<"+c+' src="'+d+'"></'+c+">")}},Mc=function(a){n.cookie=a.D+"Good";var b=Sc(a,
a.D);if(b=b=="Good"){var c=Oc(a,-1);n.cookie=a.D+"; expires="+c.toGMTString()}return b},Lc=function(a){return a=Sc(a,a.P)},Sc=function(a,b){var c=n[oa],d=c[s](b),e="";if(d!=-1){d=d+b[y];e=c[s](";",d);if(e==-1)e=c[y];e=c[H](d,e)}return e},Nc=function(a){if(a.q!=g)if(a.w){var b=new Date;b.setTime(1E3*a.q._expires_);var c=a.q._domain_;a=a.P+a.w+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;n.cookie=a}};function Tc(a,b){try{return a.top[A].URL==b.URL}catch(c){}return h};var Uc=function(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]};var Vc=new RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Wc=function(a){return a&&ea(a)};var Xc=function(a){this.pa=(this.R=a&&a.GA_jstiming)&&this.R.load};Xc[z].tick=function(a,b){this.pa.tick(a,b)};Xc[z].report=function(a){var b={};b.e=a;this.R.report(this.pa,b)};var Yc=function(){};Ra(Yc,Xc);Yc[z].tick=function(){};Yc[z].report=function(){};var Zc=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var $c=function(a,b){var c=0,d=[];a&&d[p](a);if(b){var e=Rb(b);e&&d[p](e)}if(d[y]>0)c=Pb(d[I](":"));return c[x]()};var ad=L&&o[G]()<Tb&&L.GA_jstiming&&L.GA_jstiming.load&&L.location.protocol=="http:"?new Xc(L):new Yc(L);ad.tick("js_load");function R(a){return typeof a=="function"}function bd(a,b){if(typeof a!="string"||a[y]==0)return g;else if(typeof b!="string"||b[y]==0)return g;return cd(S(),a,b)}K("GA_googleAddSlot",bd);function _GA_googleInitializeAdEngine(a){if(!W()){dd(ed(a));fd(W())}}K("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function gd(){S().sa=f;_GA_googleInitializeAdEngine(g);var a=W().g;a=="sync"||a=="sync_sra"?W().j():hd(S())}K("GA_googleFetchAds",gd);function id(){_GA_googleInitializeAdEngine("iframe");Rc(i._GA_googleCookieHelper,i.GS_googleGetIdsForAdSenseService())}K("GA_googleUseIframeRendering",id);function jd(){var a=i.GA_googleEnv[w]("google_ad_impl");a==g&&i.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}K("GA_googleUseSyncSRARendering",jd);
function kd(a){i.GA_googleEnv.setParameter("google_domain_reset_url",a)}K("GA_googleDomainResetUrl",kd);function ld(a){var b=Cb(Bb);md(S(),a,b);if(W()!=g)if(W().g!="iframe"){if(nd(W()))if(W().N){b=od(S(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(pd(W(),a)!=g&&!W().l)return;W().n(a)}}K("GA_googleFillSlot",ld);function qd(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;var e=Cb(Bb);md(S(),b,e);if(W()!=g)if(W().g=="iframe"){cd(S(),a,b);a=new rd(c,d,h,f);sd(S(),b,a);W().n(b)}}
K("GA_googleFillSlotWithSize",qd);function td(){ud(new vd(Bc));dd(g)}K("GA_googleResetAll",td);i.google_noFetch=h;function wd(){i.google_noFetch=f}K("GA_googleNoFetch",wd);function xd(){i.google_delayFetch=f}K("GA_googleDelayFetch",xd);function rd(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}ga(rd[z],function(){return"[GA_GoogleAdSlotAttr: width="+this[Ha]+", height="+this[qa]+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function yd(a){var b={};a=a[B]("?");a=a[a[y]-1][B]("&");for(var c=0;c<a[y];c++){var d=a[c][B]("=");if(d[0])try{b[d[0][Ma]()]=d[y]>1?i.decodeURIComponent?ea(d[1][r](zd," ")):unescape(d[1]):""}catch(e){}}return b}function Ad(a){a=a||n.URL;this.ma=yd(a)}Ad[z].getParameter=function(a){return a==g?g:this.ma[a]};Ad[z].setParameter=function(a,b){this.ma[a]=b};var Bd=function(){if(!bc)return"http://"+Va("","pubads.g.doubleclick.net");return"https://"+Va("","securepubads.g.doubleclick.net")};
function Cd(a){return a[r](/&/g,"&amp;")[r](/</g,"&lt;")[r](/>/g,"&gt;")[r](/\"/g,"&quot;")}function Dd(){this.G=g;this.na=h;this.Ba=(new Date)[ja]()}
var Fd=function(a,b){if(a.G==g)if(!a.na){a.G=i.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.G){var c=a.G[A],d=[];d[p]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');d[p]("<p>Google Ad Capture Window</p>");
for(var e in b)R(b[e])||d[p](Ed(a,e,b[e]));d[p]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d[p]("<script>displayTime('blocked', pageStartTime);<\/script>");d[p]("<p>Total Page Load Time (ms): <label id='total'></label>");d[p]("</body>\n</html>");d=d[I]("\n");(e=i.GA_googleEnv[w]("google_capture_norender")!=g)?c[u](Cd(d)):c[u](d);c.close()}else a.na=f}},Ed=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";var d="<p>Slot "+b+"</p>";c=c==g||c[v]==
g?"No ad":c[v];var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function Gd(a){this.d={};this.F=a}var Hd=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.F)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Id=function(a,b){for(var c in b.d)R(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};Gd[z].getAttribute=function(a){return this.d[a]};
Gd[z].h=function(){var a=[];for(var b in this.d)if(!R(this.d[b])){var c=Bc[b]||Cc[b]||Dc[b]||g,d=this.d[b];c&&d&&a[p](c+"="+M(d))}return a[I]("&")};
var Kd=function(a,b,c,d){a=Jd(a,b,c,d);b=[];a[0]&&a[0][y]>0&&b[p](a[0][I]("&"));a[1]&&a[1][y]>0&&b[p]("sps="+a[1][I]("|"));return b[I]("&")},Jd=function(a,b,c,d){var e=[],m=[];b=b.d;for(var j in d)if(!R(j)){var q=d[j];if(q){var t="";if(b[j]!=g)t=M(b[j]);var ta=[],T=-1,U=-1;for(var V in a)if(!R(a[V])){++T;if(c[V]==g)ta[p]("");else{var hb=c[V].d;if(hb[j]!=g){ta[p](M(M(hb[j])));U=T}else ta[p]("")}}if(U>=0){T=M(t);t=[];t[p](T);for(T=0;T<=U;++T)t[p](ta[T]);m[p](q+","+t[I](","))}else t&&e[p](q+"="+t)}}a=
[];a[p](e);a[p](m);return a};function Ld(a,b){this.L=a;this.s=b;this.aa=0;this.ya=this.S=this.X=h;this.wa=this.xa=this.ga=this.ta=g}var Md=function(a){a.S=f;a.ta=(new Date)[ja]()},Nd=function(a){a.ga=(new Date)[ja]()},Od=function(a){a.ya=f;a.xa=(new Date)[ja]()},Pd=function(a){a.wa=(new Date)[ja]()};ga(Ld[z],function(){return"[GA_GoogleAdSlot: pubid="+this.L+", name="+this.s+", loaded="+this.X+", tries="+this.aa+"]"});
function vd(a){this.a={};this.c=[];this.r={};this.F=a;this.la=new Gd(this.F);this.B={};this.sa=h;this.o=g;this.ca={}}
var cd=function(a,b,c){b=new Ld(b,c);return a.a[b.s]=b},Qd=function(a,b){var c=[];for(var d in a.a)if(!R(a.a[d])){if(b){var e=od(a,d);if(e==g||!e._enabled_)continue}e=a.a[d];e.S||c[p](e)}return c},Rd=function(a,b){return Qd(a,b)[y]},Sd=function(a){var b=[];for(var c in a.a){var d=a.a[c];R(d)||d.S&&d.ga==g&&b[p](c)}return b},Td=function(a){var b=0;for(var c in a.a)if(!R(a.a[c])){var d=od(a,c);d!=g&&d._enabled_&&b++}return b},Ud=function(a){for(var b in a.a)if(!R(a.a[b])){var c=a.a[b];Md(c)}},Vd=function(a,
b){var c=a.a[b];Md(c)},Wd=function(a,b){var c=a.a[b];Nd(c)},Xd=function(a,b){var c=a.a[b];Od(c)},Yd=function(a,b){var c=a.a[b];Pd(c);Zc(ad,"ga_render",a.c[y],"ga_srt")},Zd=function(a){var b=0;for(var c in a.a)R(a.a[c])||b++;return b};ga(vd[z],function(){var a="[AdData:",b=[];for(var c in this.a)R(this.a[c])||b[p](this.a[c][x]());for(var d in this.r)R(this.r[d])||b[p]("["+d+","+this.r[d]+"]");a+=b[I]();a+="]";return a});
var $d=function(a,b){return a.a[b]},ae=function(a,b,c){if(!(b==g||b[y]==0)){if(c==g||c[y]==0)c="";var d=a.r[b];a.r[b]=d==g?c:d+","+c}};function be(a,b){ae(S(),a,b)}K("GA_googleAddAttr",be);var ce=function(a,b,c){Hd(a.la,b,c)};function de(a,b){ce(S(),a,b)}K("GA_googleAddAdSensePageAttr",de);var ee=function(a){return a.la},fe=function(a,b,c,d){if(!(b==g||b[y]==0)){if(W()==g||W().g!="iframe"){var e=a.a[b];if(e==g)return}e=a.B[b];if(e==g)a.B[b]=new Gd(a.F);Hd(a.B[b],c,d)}};
function ge(a,b,c){fe(S(),a,b,c)}K("GA_googleAddAdSenseSlotAttr",ge);
var he=function(a,b){return a.B[b]},md=function(a,b,c){a.ca[b]=c},ie=function(a,b){return a.ca[b]},je=function(){var a=Bd();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},hd=function(a){if(a.o!=g)W().j();else{var b=[];for(var c in a.a)R(a.a[c])||b[p](c);a=i.GS_googleGetIdsForAdSenseService();b=je(i)+"&client="+escape(a)+"&page_slots="+escape(b[I]());n[u]("<script src = '"+b+"'><\/script>")}},ke=function(a,b){a.o=b;W().N=f;W().j()};function le(a){ke(S(),a)}
K("GA_googleSetAdSlotAttributes",le);var sd=function(a,b,c){if(a.o==g)a.o={};a.o[b]=c;W().N=f},od=function(a,b){return a.o!=g?a.o[b]:g};function me(a,b,c){if(!c||c<0||c>1)c=0;this.za=o[G]()<c;this.ua=a;this.ba=b+"/pagead/gen_204?id="+M(a);this.va=[]}
var X=function(a,b,c){if(b&&b[sa](/^\w+$/)&&c)a.ba+="&"+b+"="+M(c)},ne=function(a){var b=S();for(var c in b.a){var d=b.a[c];if(!R(d)&&d.L!=g){X(a,"pub_id",d.L);break}}X(a,"nslots",Zd(b)[x]());X(a,"pub_url",n.URL);X(a,"pub_ref",n[xa])},oe=function(a){if(!a.za||!a.ua||!a.ba)return h;var b=new Image;b.src=a.ba;a.va[p](b);return f};function Y(a){this.i=g;this.o={};this.p=this.b="";this.l=a;this.m=this.K=this.t=h;this.g="sync";this.Aa=Bc;this.u=f;this.da=this.ea=this.N=h}
var fd=function(a){a.t=i.GA_googleEnv[w]("google_nofetch")!=g||i.google_noFetch;a.K=i.GA_googleEnv[w]("google_norender")!=g;a.m=i.GA_googleEnv[w]("google_capture")!=g||i.GA_googleEnv[w]("google_capture_norender")!=g;if(a.m)a.K=f;pe(a,i);a.b=a.p;var b=Pa(a.ka,a);qe(a,i,b)},re=function(a){a.ea=f},se=function(a){a.da=f},qe=function(a,b,c){if(b[ya]){b[ya]("onload",c);return f}if(b[wa]){b[wa]("load",c,h);return f}return h};Y[z].H=function(){this.m&&Fd(i.GA_googleAdCapture,this.i)};
var te=function(a){if(a.g=="sync_sra"){var b=S(),c=Zd(b);b=b.c[y];if(c!=b){a.J=new me("sra_mismatch",Bd(),Wb);X(a.J,"correlator",a.f);X(a.J,"fslots",b[x]());ne(a.J);oe(a.J)}}},ue=function(a){ad.tick("ga_onload");ad.report(a.g)},ve=function(a){var b=Sd(S());if(b[y]>0){a.A=new me("missing_cb",Bd(),Vb);X(a.A,"pending",b[I]());X(a.A,"correlator",a.f);X(a.A,"impl",a.g);ne(a.A);oe(a.A)}};Y[z].ka=function(){ue(this);this.H();te(this);ve(this)};
var pe=function(a){var b=i.GA_googleEnv[w]("google_ad_url");if(b==g||b[y]==0)a.p=Bd()+"/gampad/ads?";else{if(b[pa](b[y]-1)!="?")b+="?";a.p=b}};Y[z].k=function(){};
var pd=function(a,b){return a.i!=g?a.i[b]:g},we=function(){var a=k[C],b=a[s]("MSIE ");return b==-1?0:parseFloat(a[H](b+5,a[s](";",b)))},zd=/\+/g,xe=function(a,b){b=b[Ma]();if(b[H](0,3)!="ca-")b="ca-"+b;return b},$=function(a,b,c){c!=g&&Z(a,b,M(c[x]()))},Z=function(a,b,c){if(c!=g&&c!="")a.b+=a.b[pa](a.b[y]-1)!="?"?"&"+b+"="+c:b+"="+c},ye=function(a,b){for(var c=Qd(S(),a.u),d=[],e=[],m=[],j=c[y],q=0;q<j;q++){var t=c[q];m[p](t.s);if(!(b!=g&&b!=t.s)){d[p](t.s);e[p](xe(a,t.L))}}$(a,"client",e[0]);if(a.l)m[y]>
0&&$(a,"page_slots",m[I]());else{$(a,"slotname",d[I]());S().c[y]>0&&$(a,"page_slots",S().c[I]())}},ze=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b[s]("google_preview=",a);c=b[s]("&",a);if(c==-1){c=b[y]-1;a-=1}return b[H](0,a)+b[H](c+1,b[y])}return b},Ae=function(a,b,c){if(Tc(b,c))return c.URL;return c[xa]},Ce=function(a,b,c){if(Be(a,b,c)!=c.URL)return c[ra];return""},Be=function(a,b,c){var d=ee(S()).getAttribute("google_page_url");if(d)return d;return Ae(a,b,c)},De=function(a,b,c,d){$(a,"url",
ze(a,Be(a,i,n),i.GA_googleEnv[w]("google_preview")));$(a,"ref",n[xa]);$(a,"lmt",(Date.parse(n.lastModified)/1E3)[x]());Z(a,"dt",b[Ba]());if(n[Ga]){b=n[Ga].scrollHeight;var e=n[Ga].clientHeight;e&&b&&$(a,"cc",o[la](e*100/b)[x]())}b=f;if(b=Ob(b)){$(a,"biw",b[ka]);$(a,"bih",b[La])}b=Uc(i);$(a,"ifi",b);b=Qb(i);b!=0&&$(a,"ifk",b[x]());if(a.da){b=$c(c,ie(S(),c));$(a,"adk",b)}b=i.GA_googleEnv[w]("deb");b!=g&&$(a,"deb",b);b=i.GA_googleEnv[w]("haonly");b!=g&&$(a,"haonly",b);b=ee(S());k[C][s]("MSIE ")>0&&Hd(b,
"google_encoding",n.charset,h);e="";if(d)e=Kd(S().a,b,S().B,a.Aa);else{c=he(S(),c);if(c==g)c=b;else Id(c,b);e=c.h()}if(e)a.b+="&"+e},Ee=function(a,b,c){var d=S().r,e=[];for(var m in d)R(d[m])||e[p](M(m)+"="+M(d[m]));$(a,"cust_params",e[I]("&"));if(b._GA_googleCookieHelper){$(a,"cookie",b._GA_googleCookieHelper.w);b._GA_googleCookieHelper.Q&&$(a,"cookie_enabled","1")}(b=Ce(a,b,c))&&$(a,"cdm",b)},Fe=function(a){Fc();var b=i;Z(a,"ga_vid",b.gaGlobal.vid);Z(a,"ga_sid",b.gaGlobal.sid);Z(a,"ga_hid",b.gaGlobal.hid);
Z(a,"ga_fc",b.gaGlobal.from_cookie);$(a,"ga_wpids",b.google_analytics_uacct)},Ge=function(a,b){for(var c in b){var d=b[c];R(d)||Z(a,c,d)}},Ke=function(a){var b=[];if(Oa(i.GS_googleGetExpIdsForAdSense)=="function"){var c=i.GS_googleGetExpIdsForAdSense();c&&b[p](c)}c=He(a.f[x]());var d=Ie(),e=Je();c&&b[p](c);d&&b[p](d);e&&b[p](e);b[y]>0&&$(a,"eid",b[I]())};
Y[z].h=function(a){this.k();Ke(this);var b=new Date;ye(this,a);Ee(this,i,n);i.GA_googleEnv[w]("google_preview")!=g&&Z(this,"gct",i.GA_googleEnv[w]("google_preview"));Fe(this);De(this,b,a,this.l);a={};Nb(a);Ge(this,a);Z(this,"flash",Lb());this.b=this.b[H](0,2E3);this.b=this.b[r](/%\w?$/,"");if(this.ea){a=this.g=="iframe"||this.g=="fallback"?"html":"json_html";Ac().registerAdBlockByType(a,this.b,f)}return this.b};
var nd=function(a){return a.u},Le=function(a,b){var c=b.getAttribute("id");return c=c.substr(18,c[y]-18)},Me=function(a,b,c,d){a='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:block;">'+d+"</ins>";return b='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:inline-table;">'+a+"</ins>"},Oe=function(a,b,c,d,e,m){var j="google_ads_iframe_"+b,q=[];b="google_ads_div_"+b;var t="border:0px;";if(Ne(i))t+="left:0;position:absolute;top:0;";q[p]("<iframe id=",
j," name=",j,' width="',e,'" height="',m,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.m?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" ','style="',t,'"',' src="',Cd(c),'"');d!=g&&q[p](' onload="',d,'"');q[p]("></iframe>");c=[];q=q[I]("");c[p]("<div id=",b,">");Ne(i)?c[p](Me(a,e,m,q)):c[p](q);c[p]("</div>");a=c[I]("");n[u](a)},Pe=function(a,b,c){var d=pd(a,c),e=d[Ha],m=d[qa];d=d[v];var j=n[va]("iframe");j.id="google_ads_iframe_"+c;j.name="google_ads_iframe_"+
c;fa(j,e);ha(j,m);j.vspace=0;j.hspace=0;j.allowTransparency="true";j.scrolling="no";j.marginWidth=0;j.marginHeight=0;j.frameBorder=0;j[E].border=0;b=n.getElementById(b);if(Ne(i)){j[E].position="absolute";j[E].top=0;j[E].left=0;var q=n[va]("ins");fa(q[E],e+"px");ha(q[E],m+"px");q[E].border=0;q[E].display="block";q[E].position="relative";var t=n[va]("ins");fa(t[E],e+"px");ha(t[E],m+"px");t[E].border=0;t[E].display="inline-table";t[E].position="relative";q[ia](j);t[ia](q);b[ia](t)}else b[ia](j);if(a.m){j[Aa][A][u](Cd(d));
j.scrolling="auto"}else j[Aa][A][u](d);Ne(i)?j[Aa][A][u]("<script>document.close();<\/script>"):j[Aa][A].close();Yd(S(),c)};function Qe(a,b){Pe(W(),a,b)}K("GA_googleCreateDomIframe",Qe);
var Re=function(){var a=[],b=n[Ca]("base");if(b)for(var c=0,d=b[y];c<d;++c){var e=b[c],m=e.getAttribute("target");if(m){a[p]({baseElement:e,originalTagValue:m});e.removeAttribute("target")}}return a},Se=function(a){if(a)for(var b=0,c=a[y];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Te=function(a){var b="http://"+Wa()+"/pagead/inject_object_div.js";if(l(we(),10)>6)return h;if(a[s](b)<0)return h;return f},Ue=function(a,b,c){if(a.m)c=Cd(c);a=Re();i.frames[b[za]].contents=
c;b.src=Te(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Se(a)},Ve=function(a,b,c){var d=Le(a,b);try{var e=b[Aa]?b[Aa][A]:b.contentDocument;if(e==g)if(n.implementation&&n.implementation.createDocument)e=n.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return h;e.open("text/html","replace");a.m?e[u](Cd(c)):e[u](c);e.close()}catch(m){return h}return f},We=function(a,
b){var c=Le(a,b),d=$d(S(),c);if(!d.X){d.X=f;d=pd(a,c);var e=b[Ka];if(d==g||d[v]==g)e.removeChild(b);else if(d._expandable_&&!(d[Ia]&&d._is_3pas_))e.innerHTML=d[v];else d._is_3pas_?Ue(a,b,d[v]):Ve(a,b,d[v]);Yd(S(),c)}},Xe=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";var d=pd(a,b);if(d!=g){c+=d[v];c+="\n</div>\n";n[u](c);Yd(S(),b)}},Ye=function(a,b){var c="google_ads_div_"+b,d="<div id="+c+">";d+="\n</div>\n";n[u](d);return c},Ze=function(a){if(!a.u)return f;if(Rd(S(),a.u)>0)return f;
else if(Td(S())==0)return h},$e=function(a,b){Zc(ad,"ga_srt",S().c[y],"_ga_start");if(a.i==g){a.i=b;for(var c in b)R(b[c])||Wd(S(),c)}else for(c in b)if(!R(b[c])){a.i[c]=b[c];Wd(S(),c)}var d=h;for(c in b)if(!R(b[c])){var e=b[c];if(d){e._cookies_=[Pc(i._GA_googleCookieHelper)];d=h}e!=g&&e._cookies_!=g&&i._GA_googleCookieHelper.M(e)}};function af(a){$e(W(),a)}K("GA_googleSetAdContentsBySlot",af);function bf(a){Y[F](this,a);this.u=h;this.f=(new Date)[Ba]();this.g=a?"sync_sra":"sync"}Ra(bf,Y);
bf[z].k=function(){this.b=this.p;$(this,"correlator",this.f[x]());Z(this,"output","json_html");Z(this,"callback","GA_googleSetAdContentsBySlotForSync");this.l?Z(this,"impl","ss"):Z(this,"impl","s");cf(this,S().c);this.l||df(this,S().c,this.i)};
var cf=function(a,b){for(var c=0,d=f,e=0;e<b[y];++e){var m=a.i&&a.i[b[e]];if(m)if(m[Ia]==ca){d=h;break}else c=2*c+(m[Ia]?1:0)}d&&Z(a,"prev_afc",c)},df=function(a,b,c){if(b&&c){for(var d=[],e=[],m=b[y]-1,j=0;j<m;j++){var q=b[j];if((q=c[q])&&q._cids_&&q._a2ids_){d[p](q._cids_[0]);e[p](q._a2ids_[0])}else{d[p]("");e[p]("")}}if(d[y]>0){b=d[I](",");e=e[I](",");$(a,"a2ids",e);$(a,"cids",b)}}},ef=function(a,b){var c=S().a;c=c[b];if(c!=g)if(!a.t){a.h(c.s);Vd(S(),b);n[u]("<script src = '"+a.b+"'><\/script>")}},
gf=function(a,b){$e(a,b);if(a.l)if(S().c[y]==1){var c=S().c[0];ff(a,c);return}for(c in b)R(b[c])||ff(a,c)};function hf(a){gf(W(),a)}K("GA_googleSetAdContentsBySlotForSync",hf);bf[z].j=function(){Ze(this)};var jf=function(a){a.h(g);n[u]("<script src = '"+a.b+"'><\/script>");Ud(S())};bf[z].n=function(a){S().c[p](a);Zc(ad,"_ga_start",S().c[y]);if(this.l)S().c[y]==1?jf(this):ff(this,a);else ef(this,a)};
var kf=function(a,b,c){if(b.google_js_backfill){a="script";c[u]("<"+a+' src="'+Db+'"></'+a+">")}},ff=function(a,b){lf(a,i,n,b)},lf=function(a,b,c,d){var e=$d(S(),d);if(e!=g){e=pd(a,d);Xd(S(),d);if(e==g||e._empty_){kf(a,b,c,d);Yd(S(),d)}else if(a.K&&!a.m)Yd(S(),d);else if(e._snippet_&&!e[Ia]&&!a.m)Xe(a,d);else if(b[Ja][C][s]("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var m="about:blank";if(b=b.GA_googleEnv[w]("google_domain_reset_url")){var j=Wc(b[sa](Vc)[3]||g);if(j===g||j[s](n[ra])>=0)m=b}Oe(a,
d,m,c,e[Ha],e[qa])}else{a=Ye(a,d);c[u]("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}},mf=function(a,b){var c=Le(a,b);$d(S(),c);We(a,b)};function nf(a){mf(W(),a)}K("GA_googleSyncAdSlotLoaded",nf);function of(a){Y[F](this,a);this.f=(new Date)[Ba]();this.g="async"}Ra(of,Y);of[z].k=function(){this.b=this.p;pf(this);$(this,"correlator",this.f[x]());Z(this,"output","json_html");Z(this,"callback","GA_googleSetAdContentsBySlot");Z(this,"impl","a")};
var pf=function(a){a.delay=500;var b=i.GA_googleEnv[w]("google_async_delay");if(b!=g)a.delay=1E3*b};of[z].j=function(){if(Ze(this))this.t||i[Fa]("GA_googleReallyFetchAds();",20)};var qf=function(a){if(Rd(S(),a.u)!=0){var b=n[Ca]("head")[0];if(a.l){var c=n[va]("script");c.src=a.h(g);b[ia](c);Ud(S())}else{var d=S().a;for(var e in d)if(!R(d[e])){c=n[va]("script");c.src=a.h(e);b[ia](c);Vd(S(),e)}}}};function rf(){qf(W())}K("GA_googleReallyFetchAds",rf);
of[z].n=function(a){var b=$d(S(),a);if(b!=g){S().c[p](a);b="GA_googleAsyncAdSlotLoaded(this);";var c=od(S(),a);Oe(this,a,"about:blank",b,c[Ha],c[qa])}};var tf=function(a,b){var c=Le(a,b);$d(S(),c);!a.t&&!a.K&&sf(a,b)};function uf(a){tf(W(),a)}K("GA_googleAsyncAdSlotLoaded",uf);var sf=function(a,b){var c=Le(a,b),d=$d(S(),c);if(a.i==g||a.i[c]==g){if(!(d.aa>30)){i[Fa](function(){sf(W(),b)},a.delay);d.aa++}}else We(a,b)};of[z].H=function(){};
function vf(a){Y[F](this,a);this.f=(new Date)[Ba]();this.g="fallback"}Ra(vf,Y);vf[z].k=function(){this.b=this.p;$(this,"correlator",this.f[x]());Z(this,"output","html");Z(this,"impl","fb")};vf[z].j=function(){Ze(this)};vf[z].z=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+M(a)}else a=this.h(a);return a};vf[z].n=function(a){var b=od(S(),a);if(b!=g){S().c[p](a);if(!this.t){var c=this.z(a);Oe(this,a,c,g,b[Ha],b[qa])}}};
function wf(a){Y[F](this,a);this.f=(new Date)[Ba]();this.N=f;this.g="iframe"}Ra(wf,Y);wf[z].k=function(){this.b=this.p;$(this,"correlator",this.f[x]());Z(this,"output","html");Z(this,"impl","ifr")};wf[z].j=function(){Ze(this)};wf[z].z=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+M(a)}else a=this.h(a);return a};wf[z].n=function(a){var b=od(S(),a);if(b!=g){S().c[p](a);if(!this.t){var c=this.z(a);Oe(this,a,c,g,b[Ha],b[qa])}}};
var xf=function(){if(Kb()){var a=we();return a<=5}else if(Ib("firefox")){var b=k[C][s]("Firefox")+8;a=l(k[C][pa](b),10);b=k[C][ma](b);return a<1}else if(Ib("safari")){b=k[C][s]("Safari")+7;b=k[C][ma](b);a=l(b,10);return a<412}else if(i[ua]!=g){b=k[C][s]("Opera")+6;b=k[C][ma](b);a=l(b,10);return a<9}else if(!Kb()&&!Ib("safari")&&Ib("mozilla")){b=k[C][s]("Netscape")+9;b=k[C][ma](b);a=l(b,10);return a<7}else return f},yf=function(){if(Kb()){var a=we();return a>5}else if(Ib("firefox")){a=k[C][s]("Firefox")+
8;var b=l(k[C][pa](a),10);k[C][ma](a);return b>1}return h},zf=function(){if(xf())return"fallback";else if(i.google_delayFetch&&yf())return"async";return"sync"},ed=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=i.GA_googleEnv[w]("google_ad_impl");if(b==g)b=zf()}switch(b){case "async":return new of(h);case "sync":return new bf(h);case "sync_sra":return new bf(f);case "fallback":return new vf(h);case "iframe":return new wf(h);default:return new vf(h)}},Af;
function S(){Af||(Af=new vd(Bc));return Af}function ud(a){delete Af;Af=a}var Bf;function W(){Bf||(Bf=g);return Bf}function dd(a){delete Bf;Bf=a}if(typeof i.GA_googleEnv=="undefined")i.GA_googleEnv=new Ad;if(typeof i.GA_googleAdCapture=="undefined")i.GA_googleAdCapture=new Dd;if(i._GA_googleCookieHelper==g)i._GA_googleCookieHelper=new Kc(g);
function He(a){var b=Ac(),c=b.getEid();if(c==""){if(c=Cf(i)){var d=b.getOsdMode();if(c=="36815006"||c=="36813008"){b.setValidOutputTypes(["html","json_html"]);d=c=="36815006"?1:0}b.setupOsd(d,c,a);(a=W())&&re(a)}}else if(c!="36815006"&&c!="36815005"&&c!="36813008"&&c!="36813007")c="";return c}function Ie(){if((i.google_unique_id||0)!=0)return i.google_expandable_exp_id;var a=Mb(["31865000","31865001"],Ub);return i.google_expandable_exp_id=a}
function Je(){if((i.google_unique_id||0)!=0)return da(i.google_adkey_exp_id||"");var a=Mb(["36816000","36816001"],Sb);i.google_adkey_exp_id=a;if(a=="36816001"){var b=W();b&&se(b)}return a}function Cf(a){if((a.google_unique_id||0)!=0)return"";a=Mb(["36815005","36815006"],Xb);if(a=="")a=Mb(["36813007","36813008"],Yb);return a}function Ne(a){return a.google_expandable_exp_id=="31865001"}ad.tick("js_parse","js_load");ad.tick("jl");})()
